spring.application.name=news-dispatcher
server.port=8081
spring.data.mongodb.uri=mongodb+srv://jasonwu:Aa131708407@cluster0.xvreqja.mongodb.net/newsdb?appName=Cluster0
spring.mongodb.uri=mongodb+srv://jasonwu:Aa131708407@cluster0.xvreqja.mongodb.net/newsdb?appName=Cluster0