spring.application.name=news-dispatcher
server.port=8081

spring.mongodb.uri=mongodb+srv://jasonwu:jason0103@cluster0.xvreqja.mongodb.net/newsdb?authSource=admin&retryWrites=true&w=majority

spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=635c8a61e85497
spring.mail.password=24d294c77d65ef
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

logging.level.org.springframework.mail=DEBUG
# 這一行會讓 Java 把跟 SMTP 伺服器對話的過程全部印在控制台
spring.mail.properties.mail.debug=true