

services:
  frontend-ui:
    image: nginx:alpine
    container_name: news-frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    restart: no

  n8n-workflow:
    image: n8nio/n8n:latest
    container_name: n8n-workflow
    ports: 
      - "5678:5678"
    environment:
      - N8N_PROTOCOL=http
      - N8N_PORT=5678
    volumes:
      - n8n_data:/home/node/.n8n
    restart: no

  news-nlp-services:
    image: news-nlp-api:latest
    container_name: news-nlp-service
    # if not docker public image, need to build:path(saved python docker file directory name)
    build: ./news-analyzer-py
    ports: 
      - "8000:8000"
    env_file:
      - ./news-analyzer-py/.env
    restart: no
  
  news-dispatcher-service:
    image: news-dispatcher-api:latest
    container_name: news-dispatcher-service
    # if not docker public image, need to build:path(saved Java docker file directory name)
    build: ./news-dispatcher
    ports: 
      - "8080:8080"
    restart: no
volumes:
 n8n_data: